dataset_params:
  im_path: r"D:\DDPM-Pytorch\data64_reshaped"

diffusion_params:
  num_timesteps : 100
  beta_start : 0.0001
  beta_end : 0.01

model_params:
  im_channels : 3
  im_size : 64
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, True]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 1
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default'
  batch_size: 1
  num_epochs: 40
  num_samples : 10
  num_grid_rows : 1
  lr: 0.0001
  ckpt_name: 'ddpm_ckpt3.pth'
